### ISSUE TITLE
Just add Sign without e functionality

### ISSUE THREAD

**Issue by metya** [alexandrelozano/PDFeSignHandwritten#1]
Hello!

Thanks for this software. 
I've sought the whole internet for a just simple tool that can sign a PDF and can do it on Windows. And there is no this thing!
And then I found your app! I thought it is what I want! 
But after trying it I realized that it is for eSign but not just adding sign annotation on PDF.

Is there a possibility to add this functionality to the app? Just adding a sign annotate to a PDF document. Without a certificate and other text stuff.

**Comment by alexandrelozano** [comment]
Hello, 
today I released a new version [PDFeSignHandwritten v1.5.5](https://github.com/alexandrelozano/PDFeSignHandwritten/releases/download/v1.5.5/PDFeSignHandwritten_v1.5.5.zip) an this have electronic signature optional (you only need to uncheck "eSign document" at top of signing properties window)

**Comment by metya** [comment]
Thank you! It is wonderful! And it works!
